ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS pipeline_stage VARCHAR(20) NOT NULL DEFAULT 'SCREENED',
  ADD COLUMN IF NOT EXISTS shortlist_tier VARCHAR(10),
  ADD COLUMN IF NOT EXISTS shortlist_position INTEGER,
  ADD COLUMN IF NOT EXISTS shortlisted_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS shortlisted_by_actor_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP;
