ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
  ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS years_of_experience INTEGER,
  ADD COLUMN IF NOT EXISTS current_job_role VARCHAR(255),
  ADD COLUMN IF NOT EXISTS current_company VARCHAR(255);
